Practising random numbers

In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [5]:
attacker_dice = np.random.randint(1, 7, size= [10,3])
defender_dice = np.random.randint(1, 7, size= [10,2])

print(attacker_dice)
print(defender_dice)

[[1 2 5]
 [1 5 4]
 [1 3 6]
 [5 6 6]
 [2 2 4]
 [3 5 6]
 [3 4 1]
 [1 2 6]
 [4 2 2]
 [5 4 4]]
[[4 5]
 [3 3]
 [2 2]
 [3 5]
 [4 3]
 [3 4]
 [4 2]
 [3 3]
 [2 1]
 [6 2]]
