Practising random numbers

In [32]:
import numpy as np
import matplotlib.pyplot as plt


In [33]:
attacker_dice = np.random.randint(1, 7, size= [10,3])
defender_dice = np.random.randint(1, 7, size= [10,2])

print(attacker_dice)
print(defender_dice)


[[2 5 2]
 [2 5 1]
 [4 6 3]
 [5 2 4]
 [3 2 4]
 [2 6 4]
 [2 3 3]
 [2 3 3]
 [2 6 4]
 [6 1 6]]
[[1 4]
 [2 4]
 [4 3]
 [2 1]
 [6 3]
 [5 2]
 [5 5]
 [4 6]
 [5 3]
 [5 4]]


In [48]:
attacker_dice = np.sort(np.random.randint(1, 7, size= [10,3]), axis=1)[:, :-1]
defender_dice = np.sort(defender_dice, axis=1)[:, ::-1]

print(attacker_dice)

[[3 5]
 [3 4]
 [4 4]
 [3 3]
 [4 4]
 [1 5]
 [2 3]
 [1 1]
 [1 4]
 [1 2]]


In [49]:
def battle(attacker_dice, defender_dice):
    attacker_losses = 0
    defender_losses = 0
    for i in range(2):
        if attacker_dice[i] > defender_dice[i]:
            defender_losses += 1
        else:
            attacker_losses += 1
    return attacker_losses, defender_losses

print(battle(attacker_dice[3], defender_dice[2]))

(2, 0)
